function MasTexto(){
        document.getElementById("par1").innerHTML="La robótica es la intersección entre la ingeniería, la tecnología y la inteligencia artificial, dedicada a diseñar y crear máquinas capaces de realizar tareas automáticas, precisas y complejas. Nuestro objetivo es aprovechar el potencial de la robótica para mejorar la eficiencia, la seguridad y la calidad de vida, facilitando labores desde entornos industriales hasta el hogar. Además, integra disciplinas como la mecánica, la electrónica y la programación para construir sistemas capaces de percibir su entorno mediante sensores, procesar información y actuar de manera autónoma o semiautónoma.\n\nLa robótica no es un concepto reciente. Desde la antigüedad han existido intentos de crear máquinas automáticas, pero fue durante el siglo XX cuando comenzó su verdadero desarrollo gracias al avance de la electrónica y la informática. Hoy en día, los robots forman parte esencial de la industria moderna, especialmente en fábricas donde realizan tareas repetitivas como ensamblaje, soldadura y empaquetado con gran precisión y velocidad.\n\nExisten distintos tipos de robots según su función. Los robots industriales trabajan en líneas de producción; los robots médicos ayudan en cirugías de alta precisión; los robots de exploración se utilizan en el espacio y en ambientes extremos como el fondo del océano; y los robots de servicio asisten en tareas domésticas, limpieza o atención al cliente. También existen robots educativos diseñados para enseñar programación y tecnología a estudiantes.\n\nUn robot está compuesto generalmente por una estructura mecánica, sensores que le permiten percibir su entorno, actuadores que ejecutan movimientos y un sistema de control programado que procesa la información y toma decisiones. Gracias a la inteligencia artificial, muchos robots modernos pueden aprender de la experiencia, adaptarse a nuevas situaciones y mejorar su desempeño con el tiempo.\n\nLas ventajas de la robótica incluyen mayor productividad, reducción de errores humanos, mayor seguridad en trabajos peligrosos y optimización de recursos. Sin embargo, también existen desafíos como el costo de implementación, la necesidad de personal capacitado y el impacto en el empleo tradicional.\n\nEn el futuro, la robótica seguirá evolucionando junto con la inteligencia artificial, la automatización y el desarrollo tecnológico. Se espera que los robots colaboren cada vez más con las personas en entornos laborales y domésticos.";
    }
function tipoRobot(){
    let tipo=prompt("Escribe: industrial, medica o servicio")
        if(tipo=="industrial"){
            alert("La robótica industrial es el tipo de robótica más desarrollado y utilizado en el mundo. Se emplea principalmente en fábricas y líneas de producción para realizar tareas como ensamblaje, soldadura, pintura y empaquetado de productos. Estos robots trabajan con gran precisión, rapidez y resistencia, lo que permite producir grandes cantidades en menos tiempo y con menos errores. Empresas automotrices como Tesla utilizan brazos robóticos avanzados en sus plantas de producción. Este tipo de robótica es fundamental para la automatización moderna y tiene un gran impacto en la economía global.");
        }
        else if(tipo=="medica"){
            alert("La robótica médica se aplica en el área de la salud para mejorar la atención y los procedimientos médicos. Se utiliza en cirugías asistidas por robot, prótesis inteligentes y procesos de rehabilitación. Uno de los sistemas más conocidos es el Da Vinci, que permite a los médicos realizar operaciones con mayor precisión y menor invasión. Gracias a esta tecnología, los pacientes pueden tener recuperaciones más rápidas y con menos riesgos. La robótica médica es importante porque contribuye a salvar vidas y a mejorar la calidad de los tratamientos.");
        }
        else if(tipo=="servicio"){
            alert("La robótica de servicio está diseñada para ayudar a las personas en tareas cotidianas, tanto en el hogar como en negocios. Incluye robots domésticos, asistentes en hoteles, restaurantes y hospitales, así como dispositivos de limpieza automática. Un ejemplo conocido es Roomba de iRobot, que limpia pisos de forma autónoma. Este tipo de robótica es cada vez más común en la vida diaria y su importancia radica en que facilita actividades rutinarias, ahorra tiempo y mejora la comodidad de las personas.");
        }
        else{
            alert("Opción erronea");
        }
    }